#!/Users/jun/miniforge3/envs/py311/bin/python3
from ultralytics import YOLO
import torch   
from matplotlib import pyplot as plt
import numpy as np  
from matplotlib import image as mpimg
import cv2
import uuid
import os
import time
import math
proxy = 'http://10.0.0.107:3128'
os.environ['http_proxy'] = proxy 
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy

# Load a model
#model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("facedetect.pt")  # load a pretrained model (recommended for training)
cap = cv2.VideoCapture('test.mp4')
if not cap.isOpened() :
    raise IOError("Cannot onen webcam")
while True:
    success, img = cap.read()
    results = model.predict(img)
    results = results[0]
    cv2.imshow('Webcam', results.plot())
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
